# fly.toml file generated for quyo-tailscale-exit on 2022-12-27T14:11:18Z

app = "quyo-tailscale-exit"
kill_signal = "SIGTERM"
kill_timeout = 15

[deploy]
  strategy = "immediate"

[env]
  PORT = "41641"

[experimental]
  auto_rollback = false
  private_network = true

[[services]]
  internal_port = 41641
  protocol = "udp"

  [[services.ports]]
    port = "41641"
